export const island = [
  {
    province: 'Camiguin',
    municipalities: [
      { city: 'Catarman' },
      { city: 'Guinsiliban' },
      { city: 'Mahinog' },
      { city: 'Mambajao' },
      { city: 'Sagay' },
    ],
  },
  {
    province: 'Basilan',
    municipalities: [
      { city: 'Akbar' },
      { city: 'Al-Barka' },
      { city: 'Hadji Mohammad Ajul' },
      { city: 'Hadji Muhtamad' },
      { city: 'Isabela City' },
      { city: 'Lamitan' },
      { city: 'Lantawan' },
      { city: 'Maluso' },
      { city: 'Sumisip' },
      { city: 'Tabuan-Lasa' },
      { city: 'Tipo-Tipo' },
      { city: 'Tuburan' },
      { city: 'Ungkaya Pukan' },
    ],
  },
  {
    province: 'Daval Del Norte',
    municipalities: [{ city: 'samal' }],
  },
  {
    province: 'Surigao Del Norte',
    municipalities: [
      { city: 'Santa Monica(Sapao)' },
      { city: 'Dapa' },
      { city: 'Burgos' },
      { city: 'Del Carmen' },
      { city: 'General Luna' },
      { city: 'Pilar' },
      { city: 'San Benito' },
      { city: 'San Isidro' },
      {
        city: 'Surigao City',
        barangay: [
          'alang-alang',
          'Alegria',
          'Aurora',
          'Baybay',
          'Bilabid',
          'Bitaugan',
          'Buenavista',
          'Cagutsan',
          'Cantiasay',
          'Catadman',
          'Danawan',
          'Day-asan',
          'Libuac',
          'Lisondra',
          'Manjagao',
          'Nonoc',
          'San Jose',
          'San Pedro',
          'Sidlakan',
          'Sugbay',
          'Talisay',
          'Zaragoza',
        ],
      },
    ],
  },
  {
    province: 'Dinagat Islands',
    municipalities: [
      { city: 'Basilisa(Rizal)' },
      { city: 'Cagdianao' },
      { city: 'Dinagat' },
      { city: 'Libjo(Albor)' },
      { city: 'Loreto' },
      { city: 'San Jose' },
      { city: 'Tubajon' },
    ],
  },
  {
    province: 'Cebu',
    municipalities: [
      { city: 'Bantayan' },
      { city: 'Madridejos' },
      { city: 'Poro' },
      { city: 'San Francisco' },
      { city: 'Santa Fe' },
      { city: 'Tudela' },
      { city: 'Pilar' },
    ],
  },
  {
    province: 'Aklan',
    municipalities: [
      { city: 'Malay', barangay: ['Balabag', 'Manoc-Manoc', 'Yapak'] },
    ],
  },
  {
    province: 'Guimaras',
    municipalities: [
      { city: 'Buenavista' },
      { city: 'Jordan' },
      { city: 'Nueva Valencia' },
      { city: 'San Lorenzo' },
      { city: 'Sibunag' },
    ],
  },
  {
    province: 'Siquijor',
    municipalities: [
      { city: 'Enrique Villanueva' },
      { city: 'Larena' },
      { city: 'Lazi' },
      { city: 'Maria' },
      { city: 'Siquijor' },
    ],
  },
  {
    province: 'Bohol',
    municipalities: [
      {
        city: 'President Carlos P. Garcia(Pitogo)',
        barangay: [
          'Aguining',
          'Basiao',
          'Baud',
          'Bayog',
          'Bogo',
          'Bonbonon',
          'Butan',
          'Campamanog',
          'Canmangao',
          'Gaus',
          'Kabangkalan',
          'Lapinig',
          'Lipata',
          'Poblacion (Pitogo)',
          'Popoo',
          'Saguise',
          'San Jose (Tawid)',
          'San Vicente',
          'Santo Rosario',
          'Tilmobo',
          'Tugas',
          'Tugnao',
          'Villa Milagrosa',
        ],
      },
    ],
  },
]
