export const picklistCity = [
  // "Camiguin",
  'Catarman',
  'Guinsiliban',
  'Mahinog',
  'Mambajao',
  'Sagay',
  // "Basilan",
  'Akbar',
  'Al-Barka',
  'Hadji Mohammad Ajul',
  'Hadji Muhtamad',
  'Isabela City',
  'Lamitan',
  'Lantawan',
  'Maluso',
  'Sumisip',
  'Tabuan-Lasa',
  'Tipo-Tipo',
  'Tuburan',
  'Ungkaya Pukan',
  // "Davao Del Norte",
  'Samal',
  // "Surigao Del Norte",
  'Santa Monica(Sapao)',
  'Dapa',
  'Burgos',
  'Del Carmen',
  'General Luna',
  'Pilar',
  'San Benito',
  'San Isidro',
  // "Dinagat Islands",
  'Basilisa(Rizal)',
  'Cagdianao',
  'Dinagat',
  'Libjo(Albor)',
  'Loreto',
  'San Jose',
  'Tubajon',
  // "Cebu",
  'Bantayan',
  'Madridejos',
  'Poro',
  'San Francisco',
  'Santa Fe',
  'Tudela',
  'Pilar',
  // "Guimaras",
  'Buenavista',
  'Jordan',
  'Nueva Valencia',
  'San Lorenzo',
  'Sibunag',
  // "Siquijor",
  'Enrique Villanueva',
  'Larena',
  'Lazi',
  'Maria',
  'Siquijor',
]
