export const picklistBarangay = [
  'alang-alang',
  'Alegria',
  'Aurora',
  'Baybay',
  'Bilabid',
  'Bitaugan',
  'Buenavista',
  'Cagutsan',
  'Cantiasay',
  'Catadman',
  'Danawan',
  'Day-asan',
  'Libuac',
  'Lisondra',
  'Manjagao',
  'Nonoc',
  'San Jose',
  'San Pedro',
  'Sidlakan',
  'Sugbay',
  'Talisay',
  'Zaragoza',
  'Balabag',
  'Manoc-Manoc',
  'Yapak',
  'Aguining',
  'Basiao',
  'Baud',
  'Bayog',
  'Bogo',
  'Bonbonon',
  'Butan',
  'Campamanog',
  'Canmangao',
  'Gaus',
  'Kabangkalan',
  'Lapinig',
  'Lipata',
  'Poblacion (Pitogo)',
  'Popoo',
  'Saguise',
  'San Jose (Tawid)',
  'San Vicente',
  'Santo Rosario',
  'Tilmobo',
  'Tugas',
  'Tugnao',
  'Villa Milagrosa',
]
