export interface TerminalsProps {
  id: string
  src: string
  name: string
  region: string
  height: number
  width: number
}

export const terminals: TerminalsProps[] = [
  {
    id: '1',
    src: '/images/storage-facilities/aurora/aurora_lpg1.webp',
    name: 'San Fabian Pangasinan',
    region: 'NLO',
    width: 1080,
    height: 800,
  },
  {
    id: '2',
    src: '/images/storage-facilities/aurora/aurora_lpg2.webp',
    name: 'San Fabian Pangasinan',
    region: 'NLO',
    width: 1080,
    height: 1620,
  },
  {
    id: '3',
    src: '/images/storage-facilities/luzon/fabian/fabian_1.webp',
    name: 'San Fabian Pangasinan',
    region: 'NLO',
    width: 1080,
    height: 720,
  },
  {
    id: '1',
    src: '/images/storage-facilities/luzon/fabian/fabian_2.webp',
    name: 'San Fabian Pangasinan',
    region: 'SLO',
    width: 1080,
    height: 721,
  },
  {
    id: '2',
    src: '/images/storage-facilities/luzon/fabian/fabian_2.webp',
    name: 'San Fabian Pangasinan',
    region: 'SLO',
    width: 1080,
    height: 1620,
  },
  {
    id: '3',
    src: '/images/storage-facilities/luzon/fabian/fabian_3.webp',
    name: 'San Fabian Pangasinan',
    region: 'SLO',
    width: 1080,
    height: 607,
  },
  {
    id: '4',
    src: '/images/storage-facilities/luzon/fabian/fabian_4.webp',
    name: 'San Fabian Pangasinan',
    region: 'SLO',
    width: 1080,
    height: 608,
  },

  {
    id: '5',
    src: '/images/storage-facilities/luzon/fabian/fabian_5.webp',
    name: 'San Fabian Pangasinan',
    region: 'SLO',
    width: 1080,
    height: 720,
  },
  {
    id: '6',
    src: '/images/storage-facilities/luzon/fabian/fabian_6.webp',
    name: 'San Fabian Pangasinan',
    region: 'SLO',
    width: 1080,
    height: 1549,
  },
  {
    id: '1',
    src: '/images/storage-facilities/visayas/ajuy/ajuy_1.webp',
    name: 'Ajuy,Iloilo',
    region: 'WVO',
    width: 1080,
    height: 720,
  },
  {
    id: '2',
    src: '/images/storage-facilities/visayas/ajuy/ajuy_2.webp',
    name: 'Ajuy,Iloilo',
    region: 'WVO',
    width: 1080,
    height: 694,
  },
  {
    id: '3',
    src: '/images/storage-facilities/visayas/ajuy/ajuy_3.webp',
    name: 'Ajuy,Iloilo',
    region: 'WVO',
    width: 1080,
    height: 1620,
  },
  {
    id: '1',
    src: '/images/storage-facilities/visayas/albuera/albuera_rs1.webp',
    name: 'Albuera, Leyte',
    region: 'EVO',
    width: 1080,
    height: 720,
  },
  {
    id: '2',
    src: '/images/storage-facilities/visayas/albuera/albuera_rs2.webp',
    name: 'Albuera, Leyte',
    region: 'EVO',
    width: 1080,
    height: 1440,
  },
  {
    id: '3',
    src: '/images/storage-facilities/visayas/albuera/albuera_rs3.webp',
    name: 'Albuera, Leyte',
    region: 'EVO',
    width: 1080,
    height: 1620,
  },
  {
    id: '1',
    src: '/images/storage-facilities/visayas/sogod/sogod_rs1.webp',
    name: 'Sogod, Cebu',
    region: 'CVO',
    width: 1080,
    height: 810,
  },
  {
    id: '2',
    src: '/images/storage-facilities/visayas/sogod/sogod_rs2.webp',
    name: 'Sogod, Cebu',
    region: 'CVO',
    width: 1080,
    height: 610,
  },
  {
    id: '3',
    src: '/images/storage-facilities/visayas/sogod/sogod_rs3.webp',
    name: 'Sogod, Cebu',
    region: 'CVO',
    width: 1080,
    height: 800,
  },
  {
    id: '1',
    src: '/images/storage-facilities/mindanao/balingasag/balingasag_rs1.webp',
    name: 'Balingasag, Misamis Oriental',
    region: 'NMO',
    width: 1080,
    height: 1620,
  },
  {
    id: '2',
    src: '/images/storage-facilities/mindanao/balingasag/balingasag_rs2.webp',
    name: 'Balingasag, Misamis Oriental',
    region: 'NMO',
    width: 1080,
    height: 608,
  },
  {
    id: '3',
    src: '/images/storage-facilities/mindanao/balingasag/balingasag_rs3.webp',
    name: 'Balingasag, Misamis Oriental',
    region: 'NMO',
    width: 1080,
    height: 810,
  },
  {
    id: '1',
    src: '/images/storage-facilities/mindanao/astorga/astorga_rs1.webp',
    name: 'Sta.Cruz, Davao Del Sur',
    region: 'SMO',
    width: 1080,
    height: 720,
  },
  {
    id: '2',
    src: '/images/storage-facilities/mindanao/astorga/astorga_rs2.webp',
    name: 'Sta.Cruz, Davao Del Sur',
    region: 'SMO',
    width: 1080,
    height: 1620,
  },
  {
    id: '3',
    src: '/images/storage-facilities/mindanao/astorga/astorga_rs3.webp',
    name: 'Sta.Cruz, Davao Del Sur',
    region: 'SMO',
    width: 1080,
    height: 610,
  },
]
